version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
