version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
    groups:
      golang-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
    groups:
      docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
