FROM golang:1.16.5 as builder
WORKDIR /go/src/github.com/mendersoftware/deployments
COPY ./ .
RUN env CGO_ENABLED=0 go test -c -o deployments-test -coverpkg $(go list ./... | grep -v vendor | grep -v mock | grep -v test | tr  '\n' ,)

FROM alpine:3.13.5
RUN apk add --no-cache ca-certificates xz-dev
RUN mkdir /etc/deployments
EXPOSE 8080

COPY ./entrypoint.sh /usr/bin/
COPY  --from=builder /go/src/github.com/mendersoftware/deployments/deployments-test /usr/bin/deployments
COPY ./config.yaml /usr/bin/

STOPSIGNAL SIGINT
ENV DEPLOYMENTS_MENDER_GATEWAY http://mender-inventory:8080
ENTRYPOINT ["/usr/bin/entrypoint.sh", "-test.coverprofile=/testing/coverage-acceptance.txt", "-acceptance-tests", "-test.run=TestRunMain", "-cli-args=server --automigrate"]
