FROM golang:1.11 as builder
RUN mkdir -p /go/src/github.com/mendersoftware/deployments
COPY . /go/src/github.com/mendersoftware/deployments
RUN cd /go/src/github.com/mendersoftware/deployments && \
     env CGO_ENABLED=0 go test -c -o deployments-test -coverpkg $(go list ./... | grep -v vendor | grep -v mock | grep -v test | tr  '\n' ,)

FROM alpine:3.4

RUN apk update && apk upgrade && \
     apk add ca-certificates xz-dev && \
     rm -rf /var/cache/apk/*

RUN mkdir /etc/deployments

EXPOSE 8080

COPY ./entrypoint.sh /usr/bin/
COPY  --from=builder /go/src/github.com/mendersoftware/deployments/deployments-test /usr/bin/deployments
COPY ./config.yaml /usr/bin/

STOPSIGNAL SIGINT
ENV DEPLOYMENTS_MENDER_GATEWAY http://mender-inventory:8080
ENTRYPOINT ["/usr/bin/entrypoint.sh", "-test.coverprofile=/testing/coverage-acceptance.txt", "-acceptance-tests", "-test.run=TestRunMain", "-cli-args=server --automigrate"]
