// Copyright 2018 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import releases "github.com/mendersoftware/deployments/resources/releases"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// GetReleases provides a mock function with given fields: ctx, filt
func (_m *Store) GetReleases(ctx context.Context, filt *releases.ReleaseFilter) ([]releases.Release, error) {
	ret := _m.Called(ctx, filt)

	var r0 []releases.Release
	if rf, ok := ret.Get(0).(func(context.Context, *releases.ReleaseFilter) []releases.Release); ok {
		r0 = rf(ctx, filt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]releases.Release)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *releases.ReleaseFilter) error); ok {
		r1 = rf(ctx, filt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
