#! /bin/sh
### BEGIN INIT INFO
# Provides:          artifacts
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Deployments service for mender.io
### END INIT INFO

# Author: Maciej Mrowiec <maciej.mrowiec@mender.io>

# Do NOT "set -e"

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Deployments service for mender.io"
NAME=deployments
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="-config=/etc/deployments/config.yaml"
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/var/log/deployments.log


# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Import functions
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

#
# Function that starts the daemon/service
#
do_start()
{
    # Check that networking is up.
    [ "$NETWORKING" = "no" ] && exit 1

    echo -n $"Starting $NAME:"
    daemon --check $NAME nohup $DAEMON $DAEMON_ARGS > $LOGFILE 2>&1 &
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$NAME
    return $RETVAL
}

#
# Function that stops the daemon/service
#
do_stop()
{
    echo -n $"Shutting down $NAME:"
    killproc $NAME
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$NAME
    return $RETVAL
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    status)
        status "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    restart|force-reload)
        do_stop
        [ $RETVAL -eq 0 ] && do_start
        ;;
    *)
        #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac
