// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package deployments

import "github.com/stretchr/testify/mock"

// MockDeploymentsModeler is an autogenerated mock type for the DeploymentsModeler type
type MockDeploymentsModeler struct {
	mock.Mock
}

// CreateDeployment provides a mock function with given fields: constructor
func (_m *MockDeploymentsModeler) CreateDeployment(constructor *DeploymentConstructor) (string, error) {
	ret := _m.Called(constructor)

	var r0 string
	if rf, ok := ret.Get(0).(func(*DeploymentConstructor) string); ok {
		r0 = rf(constructor)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*DeploymentConstructor) error); ok {
		r1 = rf(constructor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeployment provides a mock function with given fields: deploymentID
func (_m *MockDeploymentsModeler) GetDeployment(deploymentID string) (*Deployment, error) {
	ret := _m.Called(deploymentID)

	var r0 *Deployment
	if rf, ok := ret.Get(0).(func(string) *Deployment); ok {
		r0 = rf(deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Deployment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeploymentForDevice provides a mock function with given fields: deviceID
func (_m *MockDeploymentsModeler) GetDeploymentForDevice(deviceID string) (*DeploymentInstructions, error) {
	ret := _m.Called(deviceID)

	var r0 *DeploymentInstructions
	if rf, ok := ret.Get(0).(func(string) *DeploymentInstructions); ok {
		r0 = rf(deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeploymentInstructions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
