package mocks

import "github.com/stretchr/testify/mock"

import "github.com/mendersoftware/deployments/resources/deployments"

// DeploymentsModel is an autogenerated mock type for the DeploymentsModel type
type DeploymentsModel struct {
	mock.Mock
}

// CreateDeployment provides a mock function with given fields: constructor
func (_m *DeploymentsModel) CreateDeployment(constructor *deployments.DeploymentConstructor) (string, error) {
	ret := _m.Called(constructor)

	var r0 string
	if rf, ok := ret.Get(0).(func(*deployments.DeploymentConstructor) string); ok {
		r0 = rf(constructor)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*deployments.DeploymentConstructor) error); ok {
		r1 = rf(constructor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeployment provides a mock function with given fields: deploymentID
func (_m *DeploymentsModel) GetDeployment(deploymentID string) (*deployments.Deployment, error) {
	ret := _m.Called(deploymentID)

	var r0 *deployments.Deployment
	if rf, ok := ret.Get(0).(func(string) *deployments.Deployment); ok {
		r0 = rf(deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deployments.Deployment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeploymentForDevice provides a mock function with given fields: deviceID
func (_m *DeploymentsModel) GetDeploymentForDevice(deviceID string) (*deployments.DeploymentInstructions, error) {
	ret := _m.Called(deviceID)

	var r0 *deployments.DeploymentInstructions
	if rf, ok := ret.Get(0).(func(string) *deployments.DeploymentInstructions); ok {
		r0 = rf(deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deployments.DeploymentInstructions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
