// Copyright 2017 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package mocks

import context "context"
import controller "github.com/mendersoftware/deployments/resources/images/controller"
import images "github.com/mendersoftware/deployments/resources/images"
import mock "github.com/stretchr/testify/mock"
import time "time"

// ImagesModel is an autogenerated mock type for the ImagesModel type
type ImagesModel struct {
	mock.Mock
}

// CreateImage provides a mock function with given fields: ctx, multipartUploadMsg
func (_m *ImagesModel) CreateImage(ctx context.Context, multipartUploadMsg *controller.MultipartUploadMsg) (string, error) {
	ret := _m.Called(ctx, multipartUploadMsg)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *controller.MultipartUploadMsg) string); ok {
		r0 = rf(ctx, multipartUploadMsg)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *controller.MultipartUploadMsg) error); ok {
		r1 = rf(ctx, multipartUploadMsg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteImage provides a mock function with given fields: ctx, imageID
func (_m *ImagesModel) DeleteImage(ctx context.Context, imageID string) error {
	ret := _m.Called(ctx, imageID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadLink provides a mock function with given fields: ctx, imageID, expire
func (_m *ImagesModel) DownloadLink(ctx context.Context, imageID string, expire time.Duration) (*images.Link, error) {
	ret := _m.Called(ctx, imageID, expire)

	var r0 *images.Link
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) *images.Link); ok {
		r0 = rf(ctx, imageID, expire)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*images.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, imageID, expire)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditImage provides a mock function with given fields: ctx, id, constructorData
func (_m *ImagesModel) EditImage(ctx context.Context, id string, constructorData *images.SoftwareImageMetaConstructor) (bool, error) {
	ret := _m.Called(ctx, id, constructorData)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, *images.SoftwareImageMetaConstructor) bool); ok {
		r0 = rf(ctx, id, constructorData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *images.SoftwareImageMetaConstructor) error); ok {
		r1 = rf(ctx, id, constructorData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImage provides a mock function with given fields: ctx, id
func (_m *ImagesModel) GetImage(ctx context.Context, id string) (*images.SoftwareImage, error) {
	ret := _m.Called(ctx, id)

	var r0 *images.SoftwareImage
	if rf, ok := ret.Get(0).(func(context.Context, string) *images.SoftwareImage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*images.SoftwareImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListImages provides a mock function with given fields: ctx, filters
func (_m *ImagesModel) ListImages(ctx context.Context, filters map[string]string) ([]*images.SoftwareImage, error) {
	ret := _m.Called(ctx, filters)

	var r0 []*images.SoftwareImage
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []*images.SoftwareImage); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*images.SoftwareImage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ controller.ImagesModel = (*ImagesModel)(nil)
