package mocks

import (
	"github.com/mendersoftware/deployments/integration"
	"github.com/stretchr/testify/mock"
)

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

// GetDeviceInventory provides a mock function with given fields: device
func (_m *APIClient) GetDeviceInventory(device integration.DeviceID) (*integration.Device, error) {
	ret := _m.Called(device)

	var r0 *integration.Device
	if rf, ok := ret.Get(0).(func(integration.DeviceID) *integration.Device); ok {
		r0 = rf(device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integration.Device)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.DeviceID) error); ok {
		r1 = rf(device)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
