// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package mocks

import context "context"
import deployments "github.com/mendersoftware/deployments/resources/deployments"
import mock "github.com/stretchr/testify/mock"
import model "github.com/mendersoftware/deployments/resources/deployments/model"

// DeviceDeploymentLogsStorage is an autogenerated mock type for the DeviceDeploymentLogsStorage type
type DeviceDeploymentLogsStorage struct {
	mock.Mock
}

// GetDeviceDeploymentLog provides a mock function with given fields: ctx, deviceID, deploymentID
func (_m *DeviceDeploymentLogsStorage) GetDeviceDeploymentLog(ctx context.Context, deviceID string, deploymentID string) (*deployments.DeploymentLog, error) {
	ret := _m.Called(ctx, deviceID, deploymentID)

	var r0 *deployments.DeploymentLog
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *deployments.DeploymentLog); ok {
		r0 = rf(ctx, deviceID, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deployments.DeploymentLog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, deviceID, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDeviceDeploymentLog provides a mock function with given fields: ctx, log
func (_m *DeviceDeploymentLogsStorage) SaveDeviceDeploymentLog(ctx context.Context, log deployments.DeploymentLog) error {
	ret := _m.Called(ctx, log)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, deployments.DeploymentLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ model.DeviceDeploymentLogsStorage = (*DeviceDeploymentLogsStorage)(nil)
