// Copyright 2017 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package mocks

import context "context"
import images "github.com/mendersoftware/deployments/resources/images"
import mock "github.com/stretchr/testify/mock"
import model "github.com/mendersoftware/deployments/resources/deployments/model"
import time "time"

// GetRequester is an autogenerated mock type for the GetRequester type
type GetRequester struct {
	mock.Mock
}

// GetRequest provides a mock function with given fields: ctx, objectId, duration, responseContentType
func (_m *GetRequester) GetRequest(ctx context.Context, objectId string, duration time.Duration, responseContentType string) (*images.Link, error) {
	ret := _m.Called(ctx, objectId, duration, responseContentType)

	var r0 *images.Link
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) *images.Link); ok {
		r0 = rf(ctx, objectId, duration, responseContentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*images.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, string) error); ok {
		r1 = rf(ctx, objectId, duration, responseContentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ model.GetRequester = (*GetRequester)(nil)
