// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import model "github.com/mendersoftware/deployments/model"
import time "time"

// GetRequester is an autogenerated mock type for the GetRequester type
type GetRequester struct {
	mock.Mock
}

// GetRequest provides a mock function with given fields: ctx, objectId, duration, responseContentType
func (_m *GetRequester) GetRequest(ctx context.Context, objectId string, duration time.Duration, responseContentType string) (*model.Link, error) {
	ret := _m.Called(ctx, objectId, duration, responseContentType)

	var r0 *model.Link
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) *model.Link); ok {
		r0 = rf(ctx, objectId, duration, responseContentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, string) error); ok {
		r1 = rf(ctx, objectId, duration, responseContentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
