swagger: '2.0'
info:
  title: Deployments Service Device API
  version: '0.1'
  description: |
    ### Device endpoints and Authorization

    Incoming requests must set `Authorization` header and include device token
    obtained from the API. The header shall look like this:

    ```
    Authorization: Bearer <token>
    # example
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    ```
host: 'localhost:8080'
basePath: '/api/devices/0.1/deployments'
responses:
  NotFoundError: # 404
    description: Not Found
    schema:
      $ref: "#/definitions/SimpleError"
  InternalServerError: # 500
    description: Internal Server Error
    schema:
      $ref: "#/definitions/SimpleError"
  InvalidRequestError: # 400
    description: Invalid Request
    schema:
      $ref: "#/definitions/SimpleError"

paths:
  '/device/update':
    get:
      summary: List next update to be installed on the device
      parameters:
        - name: Authorization
          in: header
          description: Device ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
          examples:
            application/json:
              image:
                uri: 'https://aws.my_update_bucket.com/yocto_image123'
                checksum: cc436f982bc60a8255fe1926a450db5f195a19ad
                id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
                expire: 2016-03-11T13:03:17.063493443Z
                yocto_id: core-image-full-cmdline-20160330201408
              id: w81s4fae-7dec-11d0-a765-00a0c91e6bf6
          schema:
            type: object
            properties:
              id:
                type: string
              image:
                type: object
                properties:
                  uri:
                    type: string
                  checksum:
                    type: string
                  id:
                    type: string
                  expire:
                    type: string
                    format: date-time
                  yocto_id:
                    type: string
                required:
                  - uri
                  - id
                  - yocto_id
            required:
              - image
              - id
        204:
          description: No updates for device
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalServerError"

  '/device/deployments/{id}/status':
    put:
      summary: Update device deployment status
      description: |
        Update the status of a deployment on a particular device. Final status
        of the deployment is required to be set to indicate the success or failure
        of the installation process. Reporting of intermediate steps such as installing,
        downloading, rebooting is optional.
      parameters:
        - name: id
          in: path
          description: Deployment identifier
          required: true
          type: string
        - name: Authorization
          in: header
          description: Device ID
          required: true
          type: string
        - name: Status
          in: body
          description: Deployment status
          required: true
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                  - installing
                  - downloading
                  - rebooting
                  - success
                  - failure
            required:
              - status
      produces:
        - application/json
      responses:
        204:
          description: Status updated
        400:
          $ref: "#/responses/InvalidRequestError"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalServerError"

  '/device/deployments/{id}/log':
    put:
      summary: Upload device deployment log
      description: |
        Set deployment log. Messages are split by line in the payload.
      parameters:
        - name: id
          in: path
          description: Deployment identifier
          required: true
          type: string
        - name: Authorization
          in: header
          description: Device ID
          required: true
          type: string
        - name: Log
          in: body
          description: Deployment log
          required: true
          schema:
            type: object
            properties:
              messages:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    level:
                      type: string
                    message:
                      type: string
                  required:
                    - timestamp
                    - level
                    - message
            required:
              - messages
      produces:
        - application/json
      responses:
        204:
          description: Deployment log uploaded
        400:
          $ref: "#/responses/InvalidRequestError"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalServerError"

definitions:
  SimpleError:
    description: Simple error descriptor
    type: object
    properties:
      error:
        description: Description of error
        type: string
