swagger: '2.0'
info:
  title: Deployments v2
  version: '2'
  description: |
    Version 2 of the API for deployments management.
    Intended for use by the web GUI.

host: 'hosted.mender.io'
basePath: '/api/management/v2/deployments'
schemes:
  - https

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  ManagementJWT:
    type: apiKey
    in: header
    name: Authorization
    description: |
      API token issued by User Authentication service.
      Format: 'Bearer [JWT]'

responses:
  InvalidRequestError: # 400
    description: Bad request, see error message for details.
    schema:
      $ref: "#/definitions/Error"
  UnauthorizedError: # 401
    description: Unauthorized.
    schema:
      $ref: "#/definitions/Error"
  UnprocessableEntityError: # 422
    description: Unprocessable Entity.
    schema:
      $ref: "#/definitions/Error"
  InternalServerError: # 500
    description: Internal Server Error.
    schema:
      $ref: "#/definitions/Error"

paths:
  /deployments/releases/{release_name}/tags:
    put:
      operationId: Replace release tags
      tags:
        - Management API
      security:
        - ManagementJWT: []
      summary: |
        Update and replace the tags of a release.
      description: |
        Returns a collection of releases, allows filtering by release name and sorting
        by name or last modification date.
      parameters:
        - name: release_name
          in: path
          description: Name of the release
          required: true
          type: string
        - name: tags
          in: body
          schema:
            $ref: "#/definitions/Tags"
      produces:
        - application/json
      responses:
        204:
          description: Successful response.
        400:
          $ref: "#/responses/InvalidRequestError"
        401:
          $ref: "#/responses/UnauthorizedError"
        409:
          description: Too many unique tag keys in use.
          schema:
            $ref: "#/definitions/Error"

          examples:
            application/json:
              error: "the total number of unique tags has been exceeded"
              request_id: "f7881e82-0492-49fb-b459-795654e7188a"
        500:
          $ref: "#/responses/InternalServerError"


definitions:
  Tags:
    description: Key/value pairs for filtering resources.
    type: array
    items:
      type: object
      properties:
        key:
          type: string
          description: The name of the tag.
        value:
          type: string
          description: The tag value.

  Error:
    description: Error descriptor.
    type: object
    properties:
      error:
        description: Description of the error.
        type: string
      request_id:
        description: Request ID (same as in X-MEN-RequestID header).
        type: string
    example:
      error: "failed to decode device group data: JSON payload is empty"
      request_id: "f7881e82-0492-49fb-b459-795654e7188a"
